name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: labo03_db
          MYSQL_USER: labo03
          MYSQL_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 3306:3306

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest redis mysql-connector-python

      - name: Create .env file
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client-8.0

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL"
          sleep 15

      - name: Initialize database schema
        run: |
          mysql --protocol=tcp -h 127.0.0.1 -uroot -p${{ secrets.DB_ROOT_PASSWORD }} labo03_db < db-init/init.sql

      - name: Run tests
        run: |
          cd src
          python3 -m pytest -v


  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create .env file on VM
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

      - name: Install dependencies on VM
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run deployment script
        env:
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        run: |
          chmod +x deploy.sh
          bash deploy.sh